# -*- coding: utf-8 -*-
"""Estrategia_3_tickers_14Mar2026_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xeDyDIrli3Ak2JtX-g1EP5-F1UxG9KWC

https://www.youtube.com/watch?v=FtWx5EreiAU
"""

import pandas as pd
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
pd.options.plotting.backend = 'plotly'
import yfinance as yf

tickers = ['petr4', 'cmig4', 'bbas3']
tickers = [f'{asset}.SA' for asset in tickers]

df = yf.download(tickers, period='5y', auto_adjust=True)['Close']

prices = df.round(2)
print(prices)

retornos = prices.pct_change().dropna()
print(retornos)

ibov = yf.download('^BVSP', period='5y', auto_adjust=True)['Close']

ibov = ibov.pct_change().dropna()
ibov.columns = ['IBOV']
print(ibov)

pesos = [[0.5, 0.0, 0.5],[0.0, 0.5, 0.5],[0.5, 0.5, 0.0]]
carteiras = pd.DataFrame()
for i, peso in enumerate(pesos):
    carteiras[f'Carteira {i+1}'] = retornos.dot(peso)

carteiras = pd.concat([carteiras, ibov, retornos], axis=1)
print(carteiras)

#carteiras_normalizadas = carteiras.copy()
carteiras_normalizadas = (1 + carteiras.iloc[1:]).cumprod()
carteiras_normalizadas.iloc[0] = 1
print(carteiras_normalizadas)

(carteiras_normalizadas*100).plot(
    title='Comparativo das Carteiras',
    #labels=dict(index='Data', value='Retorno (%)'),
    labels=dict(Date='Data', value='Preço', variable='Carteiras'),
    template='plotly_dark',
)

(carteiras_normalizadas*100).plot(
    title='Comparativo das Carteiras',
    labels=dict(index='Data', value='Retorno (%)', variable='Carteiras'),
    #labels=dict(Date='Data', value='Preço', variable='Carteiras'),
    template='plotly_dark',
)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 4))
ax1.set_title('Correlação entre as Carteiras')
sns.heatmap(carteiras.corr().iloc[:3,:3],
            annot=True,
            cmap='coolwarm',
            ax=ax1,
            cbar=False)

ax2.set_title('Correlação entre os Ativos')
sns.heatmap(carteiras.corr().iloc[4:,4:],
            annot=True,
            cmap='coolwarm',
            ax=ax2,
            cbar=False)

sns.pairplot(carteiras.iloc[:, 4:])

resultados = pd.DataFrame(index=['Retorno Total', 'Volatilidade'],
                          columns=carteiras.columns)
resultados.loc['Volatilidade'] = carteiras.std()*252**0.5
resultados.loc['Retorno Total'] = carteiras_normalizadas.iloc[-1] - 1
resultados = resultados.map(lambda x: f'{x:.2%}')
print(resultados)









unique_years = df.index.year.unique().tolist()
print(unique_years)

yearly_appreciation = []

for year in unique_years:
    df_year = df[df.index.year == year]
    if not df_year.empty:
        # Check if there is enough data for the year (at least two entries)
        if len(df_year) > 1:
            appreciation_values = round(((df_year.iloc[-1] / df_year.iloc[0]) - 1) * 100, 2)
        else:
            # If only one entry, appreciation cannot be calculated, set to NaN or 0 depending on desired behavior
            appreciation_values = pd.Series([0.0]*len(df_year.columns), index=df_year.columns) # Assuming no appreciation

        # Create a dictionary for the current year's appreciation
        year_data = {'Year': year}
        year_data.update(appreciation_values.to_dict())
        yearly_appreciation.append(year_data)

# Convert the list of dictionaries to a DataFrame
yearly_appreciation_df = pd.DataFrame(yearly_appreciation)
print(yearly_appreciation_df)